spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/bootdb
    driver-class-name: org.mariadb.jdbc.Driver
    username: bootdbuser
    password: bootdbuser

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    user:
      name: user  # 테스트용 기본 사용자
      password: 1234

  output:
    ansi:
      enabled: always

  server:
    address: 0.0.0.0
    port: 8080
